repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.3
    hooks:
      - id: uv-lock
        args: ["--locked"]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.15.0
  #   hooks:
  #     - id: mypy
  #       args: [--config-file=pyproject.toml]
  #       exclude: '^(docker/)'
  #       additional_dependencies:
  #         - pydantic>=2.0

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=2000]
      - id: check-merge-conflict
      - id: trailing-whitespace
        exclude_types: ["markdown"]
      - id: end-of-file-fixer
        exclude_types: ["markdown"]
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: mixed-line-ending

  # - repo: https://github.com/adrienverge/yamllint
  #   rev: v1.37.1
  #   hooks:
  #     - id: yamllint
  #       exclude: .github
  #       args: [--strict, -c=.yamllint.yaml]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.0
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, "postgres"]
        additional_dependencies: [Flake8-pyproject]
      - id: sqlfluff-fix
        args: [--dialect, "postgres"]
        additional_dependencies: [Flake8-pyproject]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
  # Upgrade Python syntax to py3.9+
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
