"""Database helpers for the brand-masking experiment."""

from __future__ import annotations

import logging

import pandas as pd

from bias_in_llms.database.database import (
    execute_query,
    get_database_backend,
    query_db,
    sync_id_sequence,
)

TABLE_SCHEMA = "bias_in_llms"

logger = logging.getLogger(__name__)

RAW_EXPECTED_COLUMNS = {
    "run": "INTEGER NOT NULL",
    "scenario_id": "TEXT NOT NULL",
    "company_id": "TEXT NOT NULL",
    "base_scenario_text": "TEXT",
    "incumbent_name": "TEXT",
    "masked_name": "TEXT",
    "company_description": "TEXT",
    "system_prompt": "TEXT",
    "prompt_named": "TEXT",
    "prompt_masked": "TEXT",
    "response_named_raw": "TEXT",
    "response_masked_raw": "TEXT",
    "score_named": "INTEGER",
    "score_masked": "INTEGER",
    "score_delta": "REAL",
    "named_parse_success": "BOOLEAN",
    "masked_parse_success": "BOOLEAN",
    "reasoning_tokens_named": "INTEGER",
    "reasoning_tokens_masked": "INTEGER",
    "model_id": "TEXT",
    "reasoning_model": "BOOLEAN",
    "temperature": "REAL",
    "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
}

SUMMARY_EXPECTED_COLUMNS = {
    "run": "INTEGER NOT NULL",
    "model_id": "TEXT NOT NULL",
    "temperature": "REAL",
    "valid_pairs_n": "INTEGER",
    "dropped_pairs_n": "INTEGER",
    "zero_difference_pairs_n": "INTEGER",
    "mean_score_named": "REAL",
    "mean_score_masked": "REAL",
    "mean_difference": "REAL",
    "wilcoxon_statistic": "REAL",
    "p_value": "DOUBLE PRECISION",
    "conclusion": "TEXT",
    "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
}

__all__ = [
    "get_raw_full_table_name",
    "get_summary_full_table_name",
    "initialize_brand_masking_db",
    "insert_brand_masking_trial",
    "insert_brand_masking_summary",
    "brand_masking_combination_exists",
    "get_existing_brand_masking_combination",
    "select_brand_masking_trials",
    "select_brand_masking_summaries",
]


def get_raw_full_table_name(sector: str) -> str:
    """Return the fully-qualified raw table name for a given sector."""
    return f"{TABLE_SCHEMA}.brand_masking_{sector}"


def get_summary_full_table_name(sector: str) -> str:
    """Return the fully-qualified summary table name for a given sector."""
    return f"{TABLE_SCHEMA}.brand_masking_{sector}_summary"


def _raw_table_name(sector: str) -> str:
    return f"brand_masking_{sector}"


def _summary_table_name(sector: str) -> str:
    return f"brand_masking_{sector}_summary"


def _table_exists(table_name: str) -> bool:
    """Return whether a table already exists in the target schema."""
    query = """
        SELECT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = %s
            AND table_name = %s
        ) AS exists;
    """
    result_df = query_db(query, (TABLE_SCHEMA, table_name))
    return bool(result_df.to_dict("records")[0]["exists"])


def _ensure_expected_columns(
    full_table_name: str,
    table_name: str,
    columns: dict,
) -> None:
    """Add missing columns to an existing table in a safe, additive way."""
    column_exists_query = """
        SELECT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = %s
            AND table_name = %s
            AND column_name = %s
        ) AS exists;
    """

    for column_name, column_def in columns.items():
        exists_df = query_db(
            column_exists_query,
            (TABLE_SCHEMA, table_name, column_name),
        )
        if not exists_df.to_dict("records")[0]["exists"]:
            safe_def = column_def.replace(" NOT NULL", "")
            add_col_query = f"""
                ALTER TABLE {full_table_name}
                ADD COLUMN {column_name} {safe_def}
            """
            execute_query(add_col_query)


def _ensure_identity_and_sync(full_table_name: str, table_name: str) -> None:
    """Ensure the serial primary key sequence is properly configured."""
    if get_database_backend() != "postgres":
        sync_id_sequence(full_table_name)
        return

    identity_check_query = """
        SELECT is_identity, column_default
        FROM information_schema.columns
        WHERE table_schema = %s
        AND table_name = %s
        AND column_name = %s
    """

    identity_result_df = query_db(
        identity_check_query,
        (TABLE_SCHEMA, table_name, "id"),
    )
    identity_result = identity_result_df.to_dict("records")

    if identity_result:
        row = identity_result[0]
        has_no_identity = row["is_identity"] == "NO"
        has_no_default = row["column_default"] is None
        if has_no_identity and has_no_default:
            fix_identity_query = f"""
                ALTER TABLE {full_table_name}
                ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
            """
            execute_query(fix_identity_query)

    sync_id_sequence(full_table_name)


def initialize_brand_masking_db(sector: str) -> None:
    """Create or migrate the raw and summary tables for a given sector."""
    execute_query(f"CREATE SCHEMA IF NOT EXISTS {TABLE_SCHEMA}")

    raw_full = get_raw_full_table_name(sector)
    raw_name = _raw_table_name(sector)
    summary_full = get_summary_full_table_name(sector)
    summary_name = _summary_table_name(sector)

    if not _table_exists(raw_name):
        create_raw_query = f"""
            CREATE TABLE {raw_full} (
                id SERIAL PRIMARY KEY,
                run INTEGER NOT NULL,
                scenario_id TEXT NOT NULL,
                company_id TEXT NOT NULL,
                base_scenario_text TEXT,
                incumbent_name TEXT,
                masked_name TEXT,
                company_description TEXT,
                system_prompt TEXT,
                prompt_named TEXT,
                prompt_masked TEXT,
                response_named_raw TEXT,
                response_masked_raw TEXT,
                score_named INTEGER,
                score_masked INTEGER,
                score_delta REAL,
                named_parse_success BOOLEAN,
                masked_parse_success BOOLEAN,
                reasoning_tokens_named INTEGER,
                reasoning_tokens_masked INTEGER,
                model_id TEXT,
                reasoning_model BOOLEAN,
                temperature REAL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        """
        execute_query(create_raw_query)
    else:
        _ensure_expected_columns(raw_full, raw_name, RAW_EXPECTED_COLUMNS)

    if not _table_exists(summary_name):
        create_summary_query = f"""
            CREATE TABLE {summary_full} (
                id SERIAL PRIMARY KEY,
                run INTEGER NOT NULL,
                model_id TEXT NOT NULL,
                temperature REAL,
                valid_pairs_n INTEGER,
                dropped_pairs_n INTEGER,
                zero_difference_pairs_n INTEGER,
                mean_score_named REAL,
                mean_score_masked REAL,
                mean_difference REAL,
                wilcoxon_statistic REAL,
                p_value DOUBLE PRECISION,
                conclusion TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        """
        execute_query(create_summary_query)
    else:
        _ensure_expected_columns(summary_full, summary_name, SUMMARY_EXPECTED_COLUMNS)

    _ensure_identity_and_sync(raw_full, raw_name)
    _ensure_identity_and_sync(summary_full, summary_name)


def brand_masking_combination_exists(
    model_id: str,
    run: int,
    scenario_id: str,
    temperature: float,
    sector: str,
) -> bool:
    """Check whether a raw brand-masking trial already exists."""
    raw_full = get_raw_full_table_name(sector)
    query = f"""
        SELECT COUNT(*) AS count
        FROM {raw_full}
        WHERE model_id = %s
        AND run = %s
        AND scenario_id = %s
        AND temperature = %s
    """
    result_df = query_db(query, (model_id, run, scenario_id, temperature))
    result = result_df.to_dict("records")
    return result[0]["count"] > 0 if result else False


def get_existing_brand_masking_combination(
    model_id: str,
    run: int,
    scenario_id: str,
    temperature: float,
    sector: str,
) -> dict | None:
    """Fetch an existing raw trial for the given scenario/model/run tuple."""
    raw_full = get_raw_full_table_name(sector)
    query = f"""
        SELECT
            scenario_id,
            company_id,
            base_scenario_text,
            incumbent_name,
            masked_name,
            company_description,
            system_prompt,
            prompt_named,
            prompt_masked,
            response_named_raw,
            response_masked_raw,
            score_named,
            score_masked,
            score_delta,
            named_parse_success,
            masked_parse_success,
            reasoning_tokens_named,
            reasoning_tokens_masked,
            model_id,
            reasoning_model,
            temperature
        FROM {raw_full}
        WHERE model_id = %s
        AND run = %s
        AND scenario_id = %s
        AND temperature = %s
        LIMIT 1
    """
    result_df = query_db(query, (model_id, run, scenario_id, temperature))
    records = result_df.to_dict("records")
    return records[0] if records else None


def insert_brand_masking_trial(
    *,
    run: int,
    scenario_id: str,
    company_id: str,
    base_scenario_text: str,
    incumbent_name: str,
    masked_name: str,
    company_description: str,
    system_prompt: str,
    prompt_named: str,
    prompt_masked: str,
    response_named_raw: str,
    response_masked_raw: str,
    score_named: int | None,
    score_masked: int | None,
    score_delta: float | None,
    named_parse_success: bool,
    masked_parse_success: bool,
    reasoning_tokens_named: int,
    reasoning_tokens_masked: int,
    model_id: str,
    reasoning_model: bool,
    temperature: float,
    sector: str,
    debug: bool = False,
) -> None:
    """Insert one paired named-vs-masked raw trial row."""
    raw_full = get_raw_full_table_name(sector)
    query = f"""
        INSERT INTO {raw_full} (
            run, scenario_id, company_id, base_scenario_text, incumbent_name,
            masked_name, company_description, system_prompt, prompt_named,
            prompt_masked, response_named_raw, response_masked_raw, score_named,
            score_masked, score_delta, named_parse_success, masked_parse_success,
            reasoning_tokens_named, reasoning_tokens_masked, model_id,
            reasoning_model, temperature
        )
        VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
            %s, %s, %s, %s, %s, %s
        )
    """
    params = (
        run,
        scenario_id,
        company_id,
        base_scenario_text,
        incumbent_name,
        masked_name,
        company_description,
        system_prompt,
        prompt_named,
        prompt_masked,
        response_named_raw,
        response_masked_raw,
        score_named,
        score_masked,
        score_delta,
        named_parse_success,
        masked_parse_success,
        reasoning_tokens_named,
        reasoning_tokens_masked,
        model_id,
        reasoning_model,
        temperature,
    )
    execute_query(query, params)

    if debug:
        logger.info("Brand-masking trial inserted into PostgreSQL.")


def insert_brand_masking_summary(
    *,
    run: int,
    model_id: str,
    temperature: float,
    valid_pairs_n: int,
    dropped_pairs_n: int,
    zero_difference_pairs_n: int,
    mean_score_named: float | None,
    mean_score_masked: float | None,
    mean_difference: float | None,
    wilcoxon_statistic: float | None,
    p_value: float | None,
    conclusion: str,
    sector: str,
) -> None:
    """Insert one Wilcoxon summary row for a model/run combination."""
    summary_full = get_summary_full_table_name(sector)
    query = f"""
        INSERT INTO {summary_full} (
            run, model_id, temperature, valid_pairs_n, dropped_pairs_n,
            zero_difference_pairs_n, mean_score_named, mean_score_masked,
            mean_difference, wilcoxon_statistic, p_value, conclusion
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """
    params = (
        run,
        model_id,
        temperature,
        valid_pairs_n,
        dropped_pairs_n,
        zero_difference_pairs_n,
        mean_score_named,
        mean_score_masked,
        mean_difference,
        wilcoxon_statistic,
        p_value,
        conclusion,
    )
    execute_query(query, params)


def select_brand_masking_trials(
    sector: str,
    *,
    run: int | None = None,
    model_id: str | None = None,
) -> pd.DataFrame:
    """Load raw trial rows, optionally filtered by run and model."""
    raw_full = get_raw_full_table_name(sector)
    query = f"""
        SELECT *
        FROM {raw_full}
    """
    filters: list[str] = []
    params: list[str | int] = []

    if run is not None:
        filters.append("run = %s")
        params.append(run)
    if model_id is not None:
        filters.append("model_id = %s")
        params.append(model_id)

    if filters:
        query = f"{query} WHERE {' AND '.join(filters)}"

    query = f"{query} ORDER BY created_at ASC"
    return query_db(query, tuple(params) if params else None)


def select_brand_masking_summaries(sector: str) -> pd.DataFrame:
    """Load all persisted Wilcoxon summaries for the given sector."""
    summary_full = get_summary_full_table_name(sector)
    query = f"""
        SELECT *
        FROM {summary_full}
        ORDER BY created_at ASC
    """
    return query_db(query)
