"""
Database utilities specifically for the *temporal-discounting* experiment.

The goal is to keep each experiment's persistence logic neatly scoped so that
schema changes cannot accidentally break unrelated experiments.

Now uses PostgreSQL instead of SQLite.
"""

import logging
from typing import Optional

import pandas as pd

from bias_in_llms.database.database import (
    execute_query,
    query_db,
    sync_id_sequence,
)

# Constants
TABLE_SCHEMA = "bias_in_llms"
TABLE_NAME = "temporal_discounting"
FULL_TABLE_NAME = f"{TABLE_SCHEMA}.{TABLE_NAME}"

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Table initialisation
# ---------------------------------------------------------------------------


def initialize_temporal_discounting_db() -> None:  # noqa: D401
    """Initialise the PostgreSQL table for the *temporal-discounting* experiment."""
    execute_query(f"CREATE SCHEMA IF NOT EXISTS {TABLE_SCHEMA}")

    # Check if table exists
    table_exists_query = """
        SELECT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = %s
            AND table_name = %s
        ) AS exists;
    """

    result_df = query_db(
        table_exists_query,
        (TABLE_SCHEMA, TABLE_NAME),
    )
    result = result_df.to_dict("records")

    if not result[0]["exists"]:
        create_table_query = f"""
            CREATE TABLE {FULL_TABLE_NAME} (
                id SERIAL PRIMARY KEY,
                run INTEGER NOT NULL,
                now_value REAL,
                later_value REAL,
                delay_years INTEGER,
                preference TEXT,
                full_prompt TEXT,
                question TEXT,
                option_A TEXT,
                option_B TEXT,
                answer TEXT,
                model_id TEXT,
                reasoning_model BOOLEAN,
                reasoning_tokens INTEGER,
                temperature REAL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        """
        execute_query(create_table_query)
        print(f"Table {FULL_TABLE_NAME} created successfully")
    else:
        print(f"Table {FULL_TABLE_NAME} already exists")

        # Check if id column has identity (auto-increment)
        identity_check_query = """
            SELECT is_identity
            FROM information_schema.columns
            WHERE table_schema = %s
            AND table_name = %s
            AND column_name = %s
        """

        identity_result_df = query_db(
            identity_check_query,
            (TABLE_SCHEMA, TABLE_NAME, "id"),
        )
        identity_result = identity_result_df.to_dict("records")

        if identity_result and identity_result[0]["is_identity"] == "NO":
            print("Adding identity to id column...")
            fix_identity_query = f"""
                ALTER TABLE {FULL_TABLE_NAME}
                ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
            """
            execute_query(fix_identity_query)
            print("Identity added to id column successfully")

        # Synchronize sequence to start from 1 if table is empty,
        # or continue from max(id)
        print("Synchronizing ID sequence...")
        sync_id_sequence(FULL_TABLE_NAME)


# ---------------------------------------------------------------------------
# Query helpers
# ---------------------------------------------------------------------------


def combination_exists(
    model_id: str,
    run: int,
    now_value: float,
    later_value: float,
    delay_years: int,
    temperature: float,
) -> bool:
    """
    Check if a specific combination already exists in the temporal_discounting table.

    Args:
        model_id: The model identifier
        run: The run number
        now_value: The immediate value
        later_value: The delayed value
        delay_years: The delay in years
        temperature: The temperature setting

    Returns:
        True if the combination exists, False otherwise
    """
    query = f"""
        SELECT COUNT(*) as count
        FROM {FULL_TABLE_NAME}
        WHERE model_id = %s
        AND run = %s
        AND now_value = %s
        AND later_value = %s
        AND delay_years = %s
        AND temperature = %s
    """

    result_df = query_db(
        query,
        (model_id, run, now_value, later_value, delay_years, temperature),
    )
    result = result_df.to_dict("records")
    return result[0]["count"] > 0 if result else False


def get_existing_combination(
    model_id: str,
    run: int,
    now_value: float,
    later_value: float,
    delay_years: int,
    temperature: float,
) -> Optional[dict]:
    """
    Retrieve an existing combination from the temporal_discounting table.

    Args:
        model_id: The model identifier
        run: The run number
        now_value: The immediate value
        later_value: The delayed value
        delay_years: The delay in years
        temperature: The temperature setting

    Returns:
        Dictionary with the existing combination data, or None if not found
    """
    query = f"""
        SELECT preference, answer, question, full_prompt, reasoning_tokens
        FROM {FULL_TABLE_NAME}
        WHERE model_id = %s
        AND run = %s
        AND now_value = %s
        AND later_value = %s
        AND delay_years = %s
        AND temperature = %s
        LIMIT 1
    """

    result_df = query_db(
        query,
        (model_id, run, now_value, later_value, delay_years, temperature),
    )
    result = result_df.to_dict("records")

    if result:
        row = result[0]
        return {
            "preference": row["preference"],
            "answer": row["answer"],
            "question": row["question"],
            "full_prompt": row["full_prompt"],
            "reasoning_tokens": row["reasoning_tokens"],
        }

    return None


def select_all_temporal_discounting() -> pd.DataFrame:
    """
    Retrieve all rows from the temporal_discounting table.

    Returns:
        pd.DataFrame: DataFrame containing all temporal discounting experiment data
    """
    query = f"""
        SELECT
            id,
            run,
            now_value,
            later_value,
            delay_years,
            preference,
            full_prompt,
            question,
            option_A,
            option_B,
            answer,
            model_id,
            reasoning_model,
            reasoning_tokens,
            temperature,
            created_at
        FROM {FULL_TABLE_NAME}
        ORDER BY created_at ASC
    """

    return query_db(query)


# ---------------------------------------------------------------------------
# Insert helpers
# ---------------------------------------------------------------------------


def insert_temporal_discounting_row(
    model_id: str,
    run: int,
    now_value: float,
    later_value: float,
    delay_years: int,
    preference: str,
    full_prompt: str,
    question: str,
    option_A: str,
    option_B: str,
    answer: str,
    reasoning_model: bool,
    reasoning_tokens: int,
    temperature: float,
    debug: bool = False,
) -> None:
    """
    Insert a row into the temporal_discounting table.

    Args:
        model_id: The model identifier
        run: The run number
        now_value: The immediate value
        later_value: The delayed value
        delay_years: The delay in years
        preference: The preference result
        full_prompt: The full prompt text
        question: The question text
        option_A: The text for option A
        option_B: The text for option B
        answer: The answer choice
        reasoning_model: Whether reasoning model was used
        reasoning_tokens: Number of reasoning tokens
        temperature: The temperature setting
        debug: Flag to enable debug output
    """
    query = f"""
        INSERT INTO {FULL_TABLE_NAME} (
            model_id, run, now_value, later_value, delay_years, preference,
            full_prompt, question, option_A, option_B, answer,
            reasoning_model, reasoning_tokens, temperature
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """

    params = (
        model_id,
        run,
        now_value,
        later_value,
        delay_years,
        preference,
        full_prompt,
        question,
        option_A,
        option_B,
        answer,
        reasoning_model,
        reasoning_tokens,
        temperature,
    )

    execute_query(query, params)

    if debug:
        print("Temporal-discounting row inserted into PostgreSQL.")
